In [123]:
import pandas as pd
import numpy as np

1. Write a Python program to create and display a one-dimensional array-like object
containing an array of data using Pandas module.

In [124]:
data=np.array([1,2,3,4,5])
series_data=pd.Series(data)
series_data

0    1
1    2
2    3
3    4
4    5
dtype: int64

2. Write a Python program to convert a Panda module Series to Python list and it's type.

In [125]:
data2=pd.Series([1,2,3,4,5])
ls=data2.tolist()
ls

[1, 2, 3, 4, 5]

3. Write a Python program to add, subtract, multiple and divide two Pandas Series.

In [126]:
ser1=pd.Series([2,4,6,8,10])
ser2=pd.Series([1,3,5,7,9])
sum=ser1+ser2
sub=ser1-ser2
mul=ser1-ser2
div=ser1/ser2
print("Sum of arrays is: ",sum)
print("Subtraction of series is ",sub)
print("Division of series is :",div)
print("Multiplication of series is :",mul)

Sum of arrays is:  0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtraction of series is  0    1
1    1
2    1
3    1
4    1
dtype: int64
Division of series is : 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64
Multiplication of series is : 0    1
1    1
2    1
3    1
4    1
dtype: int64

4. Write a Python program to get the powers of an array values element-wise.

In [127]:
ser1=pd.Series([0,1,2,3,4,5,6])
arr=np.array([3,3,3,3,3,3,3])
ans=ser1**arr
ans

0      0
1      1
2      8
3     27
4     64
5    125
6    216
dtype: int64

5. Write a Python program to create and display a DataFrame from a specified dictionary
data which has the index labels.

In [128]:
exam_data=pd.DataFrame({
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
})
labels=pd.Series(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
exam_data.set_index(labels,inplace=True)
exam_data

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

6. Write a Python program to display a summary of the basic information about a
specified Data Frame and its data.

In [129]:
exam_data.info()
print("\n")
print(exam_data.describe())

<class 'pandas.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10 non-null     str
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64
 3   qualify   10 non-null     str
dtypes: float64(1), int64(1), str(2)
memory usage: 400.0+ bytes


           score   attempts
count   8.000000  10.000000
mean   13.562500   1.900000
std     4.693746   0.875595
min     8.000000   1.000000
25%     9.000000   1.000000
50%    13.500000   2.000000
75%    17.125000   2.750000
max    20.000000   3.000000

7. Write a Python program to get the first 3 rows of a given DataFrame.

In [130]:
exam_data.head(3)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

8. Write a Python program to select the 'name' and 'score' columns from the following
DataFrame.

In [131]:
exam_data[['name','score']]

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

9. Write a Python program to select the specified columns and rows from a given data
frame.

In [132]:
print(exam_data.loc[['b','d','f','g'],['name','score']])
print(exam_data.iloc[[1,3,5,6],[0,1]])

      name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5
      name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5

10. Write a Python program to select the rows where the number of attempts in the
examination is greater than 2.

In [133]:
exam_data[exam_data["attempts"]>2]

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

11. Write a Python program to count the number of rows and columns of a DataFrame.

In [134]:
r=len(exam_data.index)
print("Total rows :",r)
print("Total columns is:",len(exam_data.columns))

Total rows : 10
Total columns is: 4

12. Write a Python program to select the rows where the score is missing, i.e. is NaN.

In [135]:
exam_data[exam_data["score"].isnull()]

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

13. Write a Python program to select the rows where number of attempts in the
examination is less than 2 and score greater than 15.

In [136]:
exam_data[(exam_data["attempts"] <2) & (exam_data["score"]>15)]

    name  score  attempts qualify
j  Jonas   19.0         1     yes

14. Write a Python program to change the score in row 'd' to 11.5.

In [137]:
exam_data.loc['d','score']=11.5
exam_data.at['d','score']=11.5
exam_data

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

15. Write a Python program to calculate the sum of the examination attempts by the
students.

In [138]:
print("Total Attempts is :",exam_data['attempts'].sum())

Total Attempts is : 19

16. Write a Python program to calculate the mean score for each different student in
DataFrame.

In [139]:
exam_data.groupby('name')['score'].mean()
# exam_date

name
Anastasia    12.5
Dima          9.0
Emily         9.0
James        11.5
Jonas        19.0
Katherine    16.5
Kevin         8.0
Laura         NaN
Matthew      14.5
Michael      20.0
Name: score, dtype: float64

17. Write a Python program to append a new row 'k' to data frame with given values for
each column. Now delete the new row and return the original DataFrame.

In [140]:
exam_data.loc['k']=['Suresh',15.5,1,'yes']
print(exam_data)
exam_data=exam_data.drop('k')
exam_data

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Suresh   15.5         1     yes

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

18. Write a Python program to sort the DataFrame first by 'name' in descending order,
then by 'score' in ascending order.

In [141]:
exam_data=exam_data.sort_values(by=['name','score'],ascending=[False,True])
exam_data

        name  score  attempts qualify
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes

19. Write a Python program to replace the 'qualify' column contains the values 'yes' and
'no' with True and False.

In [143]:
# exam_data['qualify']=exam_data['qualify'].replace('yes','True')
# exam_data['qualify']=exam_data['qualify'].replace('no','False')
exam_data['qualify']=exam_data['qualify'].replace({'no':'False','yes':'True'})

exam_data

        name  score  attempts qualify
f    Michael   20.0         3    True
g    Matthew   14.5         1    True
h      Laura    NaN         1   False
i      Kevin    8.0         2   False
c  Katherine   16.5         2    True
j      Jonas   19.0         1    True
d      James   11.5         3   False
e      Emily    9.0         2   False
b       Dima    9.0         3   False
a  Anastasia   12.5         1    True

20. Write a Python program to delete the 'attempts' column from the DataFrame.

In [145]:
exam_data.drop(columns='attempts')

        name  score qualify
f    Michael   20.0    True
g    Matthew   14.5    True
h      Laura    NaN   False
i      Kevin    8.0   False
c  Katherine   16.5    True
j      Jonas   19.0    True
d      James   11.5   False
e      Emily    9.0   False
b       Dima    9.0   False
a  Anastasia   12.5    True

21. Write a Python program to insert a new column in existing DataFrame.

In [146]:
exam_data['attempts']=[1, 3, 2, 3, 2, 3, 1, 1, 2, 1]
exam_data

        name  score  attempts qualify
f    Michael   20.0         1    True
g    Matthew   14.5         3    True
h      Laura    NaN         2   False
i      Kevin    8.0         3   False
c  Katherine   16.5         2    True
j      Jonas   19.0         3    True
d      James   11.5         1   False
e      Emily    9.0         1   False
b       Dima    9.0         2   False
a  Anastasia   12.5         1    True

22. Write a Python program to iterate over rows in a DataFrame.

In [150]:
for index,values in exam_data.iterrows():
    print("index:",index)
    print("name:",values['name'],"score:",values['score'],'attempts:',values['attempts'])

index: f
name: Michael score: 20.0 attempts: 1
index: g
name: Matthew score: 14.5 attempts: 3
index: h
name: Laura score: nan attempts: 2
index: i
name: Kevin score: 8.0 attempts: 3
index: c
name: Katherine score: 16.5 attempts: 2
index: j
name: Jonas score: 19.0 attempts: 3
index: d
name: James score: 11.5 attempts: 1
index: e
name: Emily score: 9.0 attempts: 1
index: b
name: Dima score: 9.0 attempts: 2
index: a
name: Anastasia score: 12.5 attempts: 1

23. Write a Python program to get list from DataFrame column headers.

In [151]:
ls=list(exam_data.columns)
ls

['name', 'score', 'attempts', 'qualify']