In [138]:
import pandas as pd
import numpy as np

creating a data frame(give data in a tabular format rows and column .Can be created with dictionary,list of list)

In [139]:
data=pd.DataFrame({
    'Name':["Ram","Shyam"],
    'Age':[18,21]
})
data

    Name  Age
0    Ram   18
1  Shyam   21

creating dataframe using series data

In [140]:
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([6,7,8,9,10])
df=pd.DataFrame({'c1':s1,'c2':s2})
# put s1 data in c1 col and s2 data in c2 col as s1 and 2 ar in form of a col 1d
df

   c1  c2
0   1   6
1   2   7
2   3   8
3   4   9
4   5  10

methods of data frame

In [141]:
print("rows and col is:",df.shape)
print("Column is:",df.columns)
print("Row is:",df.dtypes) #data type of every column

rows and col is: (5, 2)
Column is: Index(['c1', 'c2'], dtype='str')
Row is: c1    int64
c2    int64
dtype: object

accessing data in data frame

In [142]:
# using labes
df.loc[0,"c1"]
# 0th row and c1 col value

np.int64(1)

In [143]:
print(df.iloc[0,1])
# for index wise access
# oth row and 1st col value

6

 information about data

In [144]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   c1      5 non-null      int64
 1   c2      5 non-null      int64
dtypes: int64(2)
memory usage: 212.0 bytes

In [145]:
df.describe()

             c1         c2
count  5.000000   5.000000
mean   3.000000   8.000000
std    1.581139   1.581139
min    1.000000   6.000000
25%    2.000000   7.000000
50%    3.000000   8.000000
75%    4.000000   9.000000
max    5.000000  10.000000

Filtering data using operators

In [146]:
df[df['c1']>2]
# show data in c1 col greater than 2

   c1  c2
2   3   8
3   4   9
4   5  10

In [147]:
df[df['c2']<8]

   c1  c2
0   1   6
1   2   7

add col,update col,delete col and much more operation on dataset

In [148]:
print(df)
df['c3']=[11,12,13,14,15]
df

   c1  c2
0   1   6
1   2   7
2   3   8
3   4   9
4   5  10

   c1  c2  c3
0   1   6  11
1   2   7  12
2   3   8  13
3   4   9  14
4   5  10  15

In [149]:
# delete a col 
print(df)
del df['c3']
print(df)

   c1  c2  c3
0   1   6  11
1   2   7  12
2   3   8  13
3   4   9  14
4   5  10  15
   c1  c2
0   1   6
1   2   7
2   3   8
3   4   9
4   5  10

In [150]:
# another way to delete
df2=df.drop(columns=['c3'])
print(df2)

KeyError: "['c3'] not found in axis"

update value from a column

In [ ]:
print(df)
df.loc[df['c1']==2]=9 #update value of 2 to 9 in c1 col
df

    index  c0
c2
6       0   1
7       1   2
8       2   3
9       3   4
10      4   5

KeyError: 'c1'

In [ ]:
# rename column name if not used inplace then changes are temporary not in original array
df.rename(columns={'c1':'c0'},inplace=True)
df

   index  c0  c2
0      0   1   6
1      1   2   7
2      2   3   8
3      3   4   9
4      4   5  10

Set a index

In [152]:
df.set_index('c2',inplace=True)
df #make c2 as index value

    c1
c2
6    1
7    2
8    3
9    4
10   5

In [154]:
df.loc[6,'c1'] #6 as index and c3 col

np.int64(1)

In [155]:
df.iloc[3,0]#3rd index from c2 and index start from 0 to n-1

np.int64(4)

In [156]:
# reset index
df.reset_index(inplace=True)

In [157]:
df

   c2  c1
0   6   1
1   7   2
2   8   3
3   9   4
4  10   5

In [162]:
ind=pd.Series([0,1,2,3,9])
df.set_index(ind,inplace=True)

In [163]:
df

   c2  c1
0   6   1
1   7   2
2   8   3
3   9   4
9  10   5

Multi dimensional data

In [165]:
data1=pd.DataFrame({
    'Park':['A','B','C','B'],
    'Name':["Ram","Shyam","Chrish","Aman"],
    'Age':[18,21,25,28]
}).set_index(['Park','Name'])
data1 #name and age is index here

             Age
Park Name
A    Ram      18
B    Shyam    21
C    Chrish   25
B    Aman     28

Selecting with condition

In [166]:
data1[data1['Age']>18] #data with age >18

             Age
Park Name
B    Shyam    21
C    Chrish   25
B    Aman     28

alternate wy of selecting with condition

In [167]:
data1.query('Age>18')

             Age
Park Name
B    Shyam    21
C    Chrish   25
B    Aman     28